version: 2

models:
  - name: dim_products
    description: "Product dimension combining Shopify products and variants"
    columns:
      - name: product_id
        description: "Unique identifier for each product"
        tests:
          - unique
          - not_null
      - name: product_name
        description: "Human-readable product title"
        tests:
          - not_null
      - name: product_tier
        description: "Hero/Accessory/Staple classification"
      - name: fit_type
        description: "Variant fit (e.g. Slim, Regular)"
      - name: fabric_type
        description: "Fabric material from metafields"

  - name: dim_customers
    description: "Customer dimension merging Shopify, Klaviyo, and GA4 profiles"
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: email
        tests:
          - not_null
      - name: loyalty_tier
        description: "Bronze/Silver/Gold tier based on order count"

  - name: dim_campaigns
    description: "Unified campaign dimension from Meta and Klaviyo"
    columns:
      - name: campaign_id
        tests:
          - unique
          - not_null
      - name: campaign_type
        description: "Awareness/Conversion/Loyalty"

  - name: fact_orders
    description: "Fact table of Shopify orders and line items"
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: order_date
        tests:
          - not_null
      - name: order_total
        tests:
          - not_null

  - name: fact_sessions
    description: "Fact table of GA4 sessions and events"
    columns:
      - name: ga_user_id
      - name: session_start_ts
        tests:
          - not_null
